/**
 * Whether the migration journal is in a state the migrator will actually act
 * on.
 *
 * ---
 *
 * **The failure this exists to prevent, because it is silent.**
 *
 * `drizzle-kit migrate` decides what to apply by comparing each journal
 * entry's `when` — which the migrator calls `folderMillis` — against the
 * single newest `created_at` already in `drizzle.__drizzle_migrations`:
 *
 * ```js
 * // drizzle-orm/pg-core/dialect.js
 * if (!lastDbMigration || Number(lastDbMigration.created_at) < migration.folderMillis) {
 * ```
 *
 * It is not a set difference. It is not keyed on the hash, the tag or the
 * index. It is one `<` against one number. So a migration whose `when` is
 * lower than the newest applied one is **skipped without a word**: no error,
 * no warning, no row written, and `db:migrate` exits zero having done
 * nothing. The operator sees the same silence a successful run produces.
 *
 * That is exactly what happened to `0010`–`0012`. `0008` and `0009` had been
 * given hand-picked round `when` values that ran ahead of real time
 * (2026-09-26 and 2026-09-27), and the three that followed were generated by
 * `drizzle-kit generate` with their real timestamps (22–23 September). All
 * three therefore sorted *before* the pilot's newest applied migration, and
 * the pilot stayed at 10 of 13 applied however many times the command was
 * run.
 *
 * **Which is why `when` is checked as an ordinal, not a date.** Nothing here
 * cares when a migration was written. What matters is that each entry's
 * number is strictly greater than the one before it, because that number is
 * the only thing deciding whether the SQL runs.
 *
 * Pure and dependency-free: the preflight guard, `db:status` and the tests
 * all read the answer from one place.
 */

export type JournalEntry = {
  idx: number;
  when: number;
  tag: string;
  breakpoints: boolean;
};

export type Journal = { entries: JournalEntry[] };

/** One thing wrong with the journal, in words an operator can act on. */
export type JournalProblem = {
  /** Which entry it is about, by tag, or null for the journal as a whole. */
  tag: string | null;
  message: string;
};

export type JournalCheck =
  | { ok: true; entries: JournalEntry[] }
  | { ok: false; problems: JournalProblem[] };

/**
 * Whatever was parsed out of `_journal.json`, checked.
 *
 * Deliberately strict about shape as well as order. A journal with a
 * malformed entry is not a journal with a warning in it — `readMigrationFiles`
 * will read `undefined` as `folderMillis`, and `undefined < n` is false, so
 * the entry is skipped just as silently as a backwards timestamp.
 */
export function checkJournal(input: unknown): JournalCheck {
  const problems: JournalProblem[] = [];

  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    return {
      ok: false,
      problems: [{ tag: null, message: "The journal is not an object." }],
    };
  }

  const entries = (input as { entries?: unknown }).entries;
  if (!Array.isArray(entries)) {
    return {
      ok: false,
      problems: [{ tag: null, message: "The journal has no entries array." }],
    };
  }
  if (entries.length === 0) {
    return {
      ok: false,
      problems: [{ tag: null, message: "The journal is empty." }],
    };
  }

  const checked: JournalEntry[] = [];
  let previous: JournalEntry | null = null;

  for (const [position, raw] of entries.entries()) {
    if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
      problems.push({
        tag: null,
        message: `Entry ${position} is not an object.`,
      });
      continue;
    }

    const entry = raw as Record<string, unknown>;
    const tag = typeof entry.tag === "string" ? entry.tag : null;

    if (!tag || tag.trim() === "") {
      problems.push({ tag: null, message: `Entry ${position} has no tag.` });
      continue;
    }

    if (typeof entry.when !== "number" || !Number.isFinite(entry.when)) {
      problems.push({
        tag,
        message: `"when" is not a number, so the migrator will never apply it.`,
      });
      continue;
    }

    if (typeof entry.idx !== "number" || !Number.isInteger(entry.idx)) {
      problems.push({ tag, message: `"idx" is not a whole number.` });
      continue;
    }

    if (entry.idx !== position) {
      problems.push({
        tag,
        message: `"idx" is ${entry.idx} but it is entry ${position} in the list.`,
      });
    }

    /*
      The tag's own number and the index must agree. They are two independent
      statements of the same ordering, and a disagreement means one of them is
      wrong — which of them is not something this can guess.
    */
    const prefix = tag.slice(0, 4);
    if (/^\d{4}$/.test(prefix) && Number(prefix) !== entry.idx) {
      problems.push({
        tag,
        message: `the file is numbered ${prefix} but its "idx" is ${entry.idx}.`,
      });
    }

    const current: JournalEntry = {
      idx: entry.idx,
      when: entry.when,
      tag,
      breakpoints: entry.breakpoints !== false,
    };

    if (previous && current.when <= previous.when) {
      problems.push({
        tag,
        message:
          `"when" is ${current.when}, which is not after ${previous.tag}'s ` +
          `${previous.when}. The migrator compares this number against the ` +
          `newest already-applied migration, so on a database that has ` +
          `${previous.tag} this one is skipped silently and never applied.`,
      });
    }

    checked.push(current);
    previous = current;
  }

  if (problems.length > 0) return { ok: false, problems };
  return { ok: true, entries: checked };
}

/**
 * The same check, against the journal on disk.
 *
 * Takes a reader rather than importing `node:fs`, so this module stays
 * importable from anywhere and the tests do not have to write files.
 */
export function checkJournalFile(
  read: (path: string) => string,
  directory = "drizzle",
): JournalCheck {
  let text: string;
  try {
    text = read(`${directory}/meta/_journal.json`);
  } catch {
    return {
      ok: false,
      problems: [
        {
          tag: null,
          message: `${directory}/meta/_journal.json could not be read.`,
        },
      ],
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return {
      ok: false,
      problems: [
        { tag: null, message: `${directory}/meta/_journal.json is not JSON.` },
      ],
    };
  }

  return checkJournal(parsed);
}

/** The refusal, as it is printed before anything touches a database. */
export function describeJournalProblems(
  problems: readonly JournalProblem[],
): string {
  const lines = [
    "The migration journal is not in a state the migrator will act on.",
    "",
  ];
  for (const problem of problems) {
    lines.push(problem.tag ? `  ${problem.tag}: ${problem.message}` : `  ${problem.message}`);
  }
  lines.push("");
  lines.push(
    "  Nothing has been applied and no database was opened. Fix",
    "  drizzle/meta/_journal.json and run the command again.",
  );
  return lines.join("\n");
}
